### ISSUE TITLE
Filter sample down to ONLY young cluster plates

### ISSUE THREAD

**Issue by kevincovey** [mscoggs/astro_ml#11]
use list from Marina to focus on Pleiades, IC 348 and Orion plates

**Comment by mkounkel** [comment]
Region       plate
pleiades     5534
pleiades     8888
ic348        6218
ic348        6219
ic348        6220
ic348        6221
ic348        6222
ic348        6223
ic348        7073
ic348        7074
ic348        7075
ic348        7079
oria         7220
oria         7221
oria         7222
oria         7223
oria         7224
oria         7225
oria         7226
oria         7227
oria         7228
oria         7229
oria         7230
oria         7231
oria         7232
oria         7233
oria         7234
laori        8879
laori        8880
laori        8885
laori        8886
orib         8890
orib         8891
orib         8894
orib         8895
orib         8896
orib         8897
orib         8905
orib         8906

Other notable plates
n1333        6224
n1333        6225
n1333        6226
n1333        7070
n1333        7071
n1333        7072
n2264        6103
n2264        6227

**Comment by mscoggs** [comment]
It looks like the field region n2264 (last two on the list Marina provided) doesn't exist in the file with the filtered IDs that Kevin put together. Is there a typo, or do you think something got lost in in the file filter?

**Comment by kevincovey** [comment]
Are you getting any matches for plates with IDs < 7000?

For instance, IC 348 and the Pleiades both have plates that are in the low
6000's and above 7000, so it could be that you are finding matches only to
the 7000+ set, which would allow you to find stars in those clusters, but
maybe not all the stars that are on the sub-7000 plates.

If it does turn out that you are only getting matches above some plate
number, I think I would recommend moving along with the process with the
matches you have, and later we can recover the missing sources and re-run
the subsequent steps.

(this is a general pattern in research, so it also means that it is best to
write code that you can re-run easily and simply, as you probably are
already doing with all your scripts).

-kevin

**Comment by mkounkel** [comment]
The issue is that the apstar file doesn't have plate information.
These are all the field names you should search for:

191-12
K2_C4_168-21
203+04
IC348
LAMBDAORI-A
LAMBDAORI-B
N1333
ORIONA
ORIONB
ORIONB-A
ORIONB-B
ORIONC
ORIOND
ORIONE
ORIONOB1AB-F
PLEIADES-E
Pleiades

Huh, the first two weren't even on my radar, but apparently they just barely overlap our targets.

**Comment by mscoggs** [comment]
Great, thank you!
