### ISSUE TITLE
Construct K-8 micron color & use to remove stars w/ disk excesses

### ISSUE THREAD

**Issue by kevincovey** [mscoggs/astro_ml#13]
See, e.g., Figs. 7 & 8 of Teixeira+ 2012 [http://adsabs.harvard.edu/abs/2012A%26A...540A..83T] for location of disked sources in J-H vs. K-8 micron space

**Comment by mkounkel** [comment]
Spitzer identification in the relevant regions:
http://adsabs.harvard.edu/abs/2007AJ....134..411M
http://adsabs.harvard.edu/abs/2012AJ....144..192M
http://adsabs.harvard.edu/abs/2007ApJ...662.1067H
http://adsabs.harvard.edu/abs/2010ApJ...722.1226H

WISE would need to be added separately
