### ISSUE TITLE
Use location in J-K vs. M_K CMD to infer Teff & log g [assume solar Fe/H]

### ISSUE THREAD

**Issue by kevincovey** [mscoggs/astro_ml#14]

**Comment by mkounkel** [comment]
![hr](https://user-images.githubusercontent.com/6738789/48450877-c735cf00-e75c-11e8-9d5e-30740d60dc4e.jpg)
![massk](https://user-images.githubusercontent.com/6738789/48450881-c8ff9280-e75c-11e8-88bb-c2cc99f21679.jpg)

[parsecgrid.pickle.zip](https://github.com/mscoggs/astro_ml/files/2578608/parsecgrid.pickle.zip)

Figures:
1) HR diagram showing isochrones for 1, 5, 10, 50, 100, 500 Myr and 1 Gyr, and masses from 0.1 to 1 Msun in 0.1 Msun steps.
2) Mass vs M_K, same ages as before

Attaching the isochrone grid, in a pickle format. To read it (after unzipping, assuming python 2)
import pickle
parsecgrid = pickle.load( open( "parsecgrid.pickle", "r" ) )
-Contains a dictionary of various parameters
mini (aka initial mass) & age are the fundamental dimensions, everything else is an array in respect to them. Includes teff, logg, jmag, hmag, and kmag, among a few other interpolated parameters.
