### ISSUE TITLE
Infer metallicity from photometry

### ISSUE THREAD

**Issue by kevincovey** [mscoggs/astro_ml#7]
Calculate [Fe/H] for main sequence stars from either J-H vs. H-K relationship (see Leggett+ 1992 and Fig. 12 of Terrien+ 2015 [http://adsabs.harvard.edu/abs/2015ApJS..220...16T]) or g-K vs. J-K (see Hejazdi+ 2015  http://adsabs.harvard.edu/abs/2015AJ....149..140H)

**Comment by mkounkel** [comment]
All the color information is saved in allstar_HugeTable.fits, retaining all info from the GaiaAPOGEE_HugeTable_wDistMod.fits
Three surveys are included: SDSS DR12 (suffix _sdss, eg, gmag_sdss, ~40% of all sources), APASS DR9 (suffix _apass, eg, gpmag_apass, ~60% of all sources), and PanSTARRS DR1 (suffix _pan, eg, gmag_pan, also has gKmag_pan, which is slightly different, the former one is PSF magnitude, the latter one is Kron?, ~90% of all sources).

Fun thing to keep in mind, g magnitudes are in the AB scale, and not in Vega.

**Comment by kevincovey** [comment]
A comment I made to Erin off-line, but which I'll preserve here: If 90% of the sources have PanSTARRS photometry, I recommend moving forward with just the sources that DO have PanSTARRS photometry for now, and we can determine if/how we want to back-fill the other 10% later.

**Comment by kevincovey** [comment]
And I recommend using equation 1 on page 5 of Hejazdi+ 2015, with coefficients listed in the following column of that page, to generate metallicities for each star based on its g-K and J-K photometry.

This relationship is only calibrated for stars in the color space shown in Figure 2 of Hejazdi+ (i.e., 3 < g-K < 9 and 0.7 < J-K < 1.05).  Still, probably worth computing for all stars, and then seeing how the comparison with the Payne FeH values holds up as a function of g-K color.
