### ISSUE TITLE
Infer mass (and then Teff?) from M_K 

### ISSUE THREAD

**Issue by kevincovey** [mscoggs/astro_ml#8]
Use relationship from Benedict+ 2016 [http://adsabs.harvard.edu/abs/2016AJ....152..141B] to infer mass from M_K; use either model isochrone or Mann+ 2015 to infer Teff from Mass.

**Comment by mscoggs** [comment]
We couldn't find an equation that relates T_eff and mass. Did you mean Teff and Fe/H? We found an equation (#6) that relates the two in : https://arxiv.org/pdf/1501.01635.pdf which is what we assumed was Mann+ 2015.
